baseURL = 'https://example.org/'
languageCode = 'en-us'
title = '0xcf9'
theme = "hello-friend-ng"
paginate = 10
showAllPostsArchive = true

[menus]
    [[menus.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    [[menus.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    [[menus.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
